### ISSUE TITLE
Feature mismatch

### ISSUE THREAD

**Issue by JeS24** [thread-pond/signature-pad#210]
Hello,

I found this plugin on JQueryScript.net, [here](https://www.jqueryscript.net/other/Smooth-Signature-Pad-Plugin-with-jQuery-Html5-Canvas.html), which linked me to this repo. However, the version, that they are using in their examples, has features, that the version, in this repo, doesn't. For example, Bezier Interpolation, as can be seen in the examples [here](https://www.jqueryscript.net/demo/Smooth-Signature-Pad-Plugin-with-jQuery-Html5-Canvas/examples/). In fact, the code from this repo has no mention of interpolation. Has the codebase been shifted to some other CVS, or is something else going on here? Can somebody explain, what I am missing here?

Regards,
JeS

**Comment by mockdeep** [comment]
@JeS24 I honestly have no idea what is going on with that. I'm not able to find any reference to it in the code, either. This is the canonical signature-pad repo, but it hasn't been very well maintained for quite a while. We adopted it because we use it internally, but unfortunately haven't had much time to work on it. It's baffling to me where those might have come from, but I'd love to know. They do use [bezier.js](https://github.com/Pomax/bezierjs), but that doesn't seem to have any reference to the particular configuration either. There aren't any branches on this repo that would have that code. The only thing I can think of is that maybe it's from [one of our forks](https://github.com/thread-pond/signature-pad/network), but good luck hunting that down.

**Comment by mockdeep** [comment]
Maybe @thomasjbradley has an idea?

**Comment by thomasjbradley** [comment]
Huh. Couldn’t say.

**Comment by JeS24** [comment]
@mockdeep @thomasjbradley Following @mockdeep’s suggestion, I looked into the forks and one of them had many more forks. I checked the code and voila: https://github.com/ezl/signature-pad. I think, the code JQueryScript.net is using, is a further updated version, but it is certainly based on ezl’s fork.
